esphome:
  name: bed-room

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_key

ota:
  password: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed-Room Fallback Hotspot"
    password: "tyhKnSjEaJwz"

captive_portal:

sensor:
  - platform: dht
    model: DHT11
    pin: GPIO05
    temperature:
      id: mysensor
      name: "Bed Room Temperature"
    humidity:
      name: "Bed Room Humidity"
    update_interval: 5s

remote_transmitter:
  pin: GPIO04
  carrier_duty_percent: 50%

climate:
  - platform: heatpumpir
    name: "Bed Room AC"
    protocol: samsung_fjm
    min_temperature: 25
    max_temperature: 28
    vertical_default: mdown
    horizontal_default: middle
    sensor: mysensor
