esphome:
  name: bed-room-sm

esp8266:
  board: esp01

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_key

ota:
  password: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed-Room-SM Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# dallas:
#   - pin: GPIO2
#     update_interval: 5s
# sensor:
#   - platform: dallas
#     address: 0xa7000444267fff28
#     name: "Bed Room Temperature"
#     id: mysensor

sensor:
  - platform: dht
    model: DHT11
    pin: GPIO2
    temperature:
      id: mysensor
      name: "Bed Room Temperature"
    humidity:
      name: "Bed Room Humidity"
    update_interval: 5s

remote_transmitter:
  pin: GPIO3
  carrier_duty_percent: 50%

climate:
  - platform: heatpumpir
    name: "Bed Room SM AC"
    protocol: samsung_fjm
    min_temperature: 25
    max_temperature: 28
    vertical_default: mdown
    horizontal_default: middle
    sensor: mysensor
