esphome:
  name: living-room

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_key

ota:
  password: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living-Room Fallback Hotspot"
    password: "uARdnkhFSS6d"

captive_portal:

switch:
  - platform: gpio
    name: "Switch 1"
    pin:
      number: 4
      inverted: true

  - platform: gpio
    name: "Switch 2"
    pin:
      number: 5
      inverted: true
